const PDFDocument = require('pdfkit');

function generateModernResume(doc, content) {
  doc.fontSize(28).font('Helvetica-Bold').text('Professional Resume', { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(12).font('Helvetica').text(content, { align: 'left', lineGap: 8 });
  doc.moveDown();
  doc.fontSize(10).text('Generated by ProATS - 2026 Ready', { align: 'center' });
}

function generateCorporateResume(doc, content) {
  doc.fontSize(22).text('Corporate Profile', { align: 'center' });
  doc.moveDown(1.5);
  doc.fontSize(11).text(content);
}

module.exports = { generateModernResume, generateCorporateResume };
